definitions:
  config:
    /hippo:configuration:
      jcr:primaryType: hipposys:configuration
      /hippo:derivatives:
        jcr:primaryType: hipposys:derivativesfolder
        /hippo:corederivatives:
          jcr:primaryType: hipposys:deriveddefinition
          hipposys:classname: org.hippoecm.repository.deriveddata.CoreDerivedDataFunction
          hipposys:nodetype: hippo:document
          hipposys:serialver: 1
          /hipposys:accessed:
            jcr:primaryType: hipposys:propertyreferences
            /ancestors:
              jcr:primaryType: hipposys:builtinpropertyreference
              hipposys:method: ancestors
          /hipposys:derived:
            jcr:primaryType: hipposys:propertyreferences
            /ancestors:
              jcr:primaryType: hipposys:relativepropertyreference
              hipposys:relPath: hippo:paths
      /hippo:temporary:
        .meta:category: system
      /hippo:queries:
        jcr:primaryType: hipposys:queryfolder
      /hippo:workflows:
        jcr:primaryType: hipposys:workflowfolder
        jcr:uuid: c89f56e5-5e9d-4967-9850-7b6254d1791c
      /hippo:domains:
        jcr:primaryType: hipposys:domainfolder
        /everywhere:
          jcr:primaryType: hipposys:domain
          /all-nodes:
            jcr:primaryType: hipposys:domainrule
            /match-all-types:
              jcr:primaryType: hipposys:facetrule
              hipposys:equals: true
              hipposys:facet: jcr:primaryType
              hipposys:filter: false
              hipposys:type: Name
              hipposys:value: '*'
          /admin:
            jcr:primaryType: hipposys:authrole
            hipposys:userrole: xm-admin
            hipposys:role: admin
          /readonly:
            jcr:primaryType: hipposys:authrole
            hipposys:userrole: xm-read-everywhere
            hipposys:role: readonly
      /hippo:security:
        jcr:primaryType: hipposys:securityfolder
        /internal:
          jcr:primaryType: hipposys:securityprovider
          hipposys:classname: org.hippoecm.repository.security.RepositorySecurityProvider
          /hipposys:userprovider:
            jcr:primaryType: hipposys:userprovider
            hipposys:dirlevels: 0
          /hipposys:groupprovider:
            jcr:primaryType: hipposys:groupprovider
            hipposys:dirlevels: 0
        /hipposys:accessmanager:
          jcr:primaryType: hipposys:accessmanager
          hipposys:permissioncachesize: 20000
      /hippo:users:
        jcr:primaryType: hipposys:userfolder
        .meta:residual-child-node-category: system
        /admin:
          jcr:primaryType: hipposys:user
          hipposys:active: true
          hipposys:password:
            .meta:category: system
            value: $SHA-256$HIlytXwnqSU=$NqCi2sJoM4qAwQ8136GYueUVA/TSyidpAI3Evn+y/hc=
          hipposys:securityprovider: internal
          hipposys:passwordlastmodified:
            .meta:category: system
          hipposys:previouspasswords:
            .meta:category: system
          hipposys:userroles:
            .meta:category: system
            value: [xm-admin]
        /workflowuser:
          jcr:primaryType: hipposys:user
          hipposys:active: true
          hipposys:system: true
          hipposys:password:
            .meta:category: system
            value: $SHA-256$*
          hipposys:securityprovider: internal
          hipposys:passwordlastmodified:
            .meta:category: system
          hipposys:previouspasswords:
            .meta:category: system
          hipposys:userroles:
            .meta:category: system
            value: [xm-admin]
        /ping-user:
          jcr:primaryType: hipposys:user
          hipposys:active: true
          hipposys:passkey: jvm://
          hipposys:securityprovider: internal
          hipposys:system: true
      /hippo:groups:
        jcr:primaryType: hipposys:groupfolder
        .meta:residual-child-node-category: system
        /admin:
          jcr:primaryType: hipposys:group
          hipposys:members:
            .meta:category: system
            value: []
          hipposys:userroles:
            .meta:category: system
            value: [xm-admin]
          hipposys:securityprovider: internal
      /hippo:roles:
        jcr:primaryType: hipposys:rolefolder
        .meta:residual-child-node-category: system
        /admin:
          jcr:primaryType: hipposys:role
          hipposys:privileges: ['jcr:all', 'hippo:admin']
          hipposys:roles: [editor]
      /hippo:userroles:
        jcr:primaryType: hipposys:userrolefolder
        .meta:residual-child-node-category: system
        /xm-security-manager:
          jcr:primaryType: hipposys:userrole
          hipposys:system: true
        /xm-security-user-manager:
          jcr:primaryType: hipposys:userrole
          hipposys:system: true
          hipposys:userroles: [xm-security-manager]
        /xm-security-application-manager:
          jcr:primaryType: hipposys:userrole
          hipposys:system: true
          hipposys:userroles: [xm-security-manager]
        /xm-admin:
          jcr:primaryType: hipposys:userrole
          hipposys:system: true
          hipposys:userroles: [xm-security-user-manager, xm-security-application-manager]
        /xm-read-everywhere:
          jcr:primaryType: hipposys:userrole
          hipposys:system: true
      /hippo:frontend:
        jcr:primaryType: hipposys:applicationfolder
      /hippo:modules:
        jcr:primaryType: hipposys:modulefolder
        jcr:lockOwner:
          .meta:category: system
        jcr:lockIsDeep:
          .meta:category: system
