#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
definitions:
  config:
    /hst:hst/hst:configurations/${rootArtifactId.replace($hyphen,$empty)}/hst:workspace/hst:channel:
      jcr:primaryType: hst:channel
      hst:name: ${projectName}
      hst:type: website
      /hst:channelinfo:
        jcr:primaryType: hst:channelinfo
