#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
/content/documents/${rootArtifactId.replace($hyphen,$empty)}:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['mix:referenceable', 'hippotranslation:translated', 'hippo:named']
  jcr:uuid: 996bcac5-86cf-49b5-a7a3-16a74863e814
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: 996bcac5-86cf-49b5-a7a3-16a74863e814
  hippotranslation:locale: en
  hippo:name: ${projectName}
