definitions:
  config:
    /hippo:configuration/hippo:users/configuser:
      jcr:primaryType: hipposys:user
      hipposys:active: true
      hipposys:passkey: jvm://
      hipposys:userroles: [xm.repository.reader]
      hipposys:securityprovider: internal
      hipposys:system: true
