definitions:
  config:
    /hst:hst/hst:configurations:
      /taxonomydemo-common:
        jcr:primaryType: hst:configuration
      /taxonomydemo-en:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../taxonomydemo-common]
      /taxonomydemo-fr:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../taxonomydemo-common]
      /taxonomydemo-nl:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../taxonomydemo-common]
