definitions:
  config:
    /hippo:configuration/hippo:domains/content-read:
      jcr:primaryType: hipposys:domain
      /documents-domain:
        jcr:primaryType: hipposys:domainrule
        /content-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /content
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor, author]
        hipposys:role: readonly
