definitions:
  config:
    /hippo:configuration/hippo:domains/folders:
      jcr:primaryType: hipposys:domain
      /content-folders-domain:
        jcr:primaryType: hipposys:domainrule
        /content-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /content
        /nodetype-hippostd-folder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hippostd:folder
      /content-directories-domain:
          jcr:primaryType: hipposys:domainrule
          /content-and-descendants:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:path
            hipposys:filter: false
            hipposys:type: Reference
            hipposys:value: /content
          /nodetype-hippostd-folder:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: nodetype
            hipposys:filter: false
            hipposys:type: Name
            hipposys:value: hippostd:directory
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor, author]
        hipposys:role: readwrite
      # even though no groups assigned, this is handy for downstream projects so not one specific downstream project has
      # to create the 'readonly' authrole
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: []
        hipposys:role: readonly
      /author:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [author]
        hipposys:role: author
      /editor:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor]
        hipposys:role: editor
