definitions:
  config:
    /hippo:configuration/hippo:domains/versioning:
      jcr:primaryType: hipposys:domain
      /nt-system:
        jcr:primaryType: hipposys:domainrule
        /type-rep-system:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /jcr:system
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [everybody]
        hipposys:role: readonly
      /editor:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor]
        hipposys:role: editor
