# TODO only for 'cmsusers' instead of 'everybody' should be enough
definitions:
  config:
    /hippo:configuration/hippo:domains/hippo-namespaces-read:
      jcr:primaryType: hipposys:domain
      /hippo-namespaces-domain:
        jcr:primaryType: hipposys:domainrule
        /hippo-namespaces-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:namespaces
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [everybody]
        hipposys:role: readonly
