definitions:
  config:
    /hippo:configuration/hippo:domains/assets-gallery-items-readwrite:
      jcr:primaryType: hipposys:domain
      /gallery-domain:
        jcr:primaryType: hipposys:domainrule
        /gallery-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:type: Reference
          hipposys:value: /content/gallery
        /gallery-item:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hippo:availability
          hipposys:type: String
          hipposys:value: live
      /assets-domain:
        jcr:primaryType: hipposys:domainrule
        /assets-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:type: Reference
          hipposys:value: /content/assets
        /asset-item:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hippo:availability
          hipposys:type: String
          hipposys:value: live
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm-content-author
        hipposys:role: readwrite
