definitions:
  config:
    /hippo:configuration/hippo:domains/modify-self:
      jcr:primaryType: hipposys:domain
      /self:
        jcr:primaryType: hipposys:domainrule
        /match-nodename-with-username:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodename
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: __user__
        /type-hippo-user:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hipposys:user
      /modify:
        jcr:primaryType: hipposys:authrole
        # TODO Maybe we should have a separate userrole like 'xm-user' for this, not correlating to content authoring
        # TODO which is always assigned to logged in users (not-anonymous users)?
        # TODO Or instead support hipposys:users: [*] matching any non-anonymous user?
        hipposys:userrole: xm-content-author
        hipposys:role: modify
