definitions:
  config:
    /hippo:configuration/hippo:domains/draft-document-holder-readwrite:
      jcr:primaryType: hipposys:domain
      /holder-domain:
        jcr:primaryType: hipposys:domainrule
        /if-holder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hippostd:holder
          hipposys:type: String
          hipposys:value: __user__
        /draft-only:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hippostd:state
          hipposys:type: String
          hipposys:value: draft
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm.content.holder
        hipposys:role: readwrite
