definitions:
  config:
    /hippo:configuration/hippo:domains/content:
      jcr:primaryType: hipposys:domain
      /content-domain:
        jcr:primaryType: hipposys:domainrule
        /content-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /content
      /author:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm-content-author
        hipposys:role: author
      /editor:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm-content-editor
        hipposys:role: editor
      # even though the userrole xm-content-reader isn't assigned by default, this is handy for downstream projects
      # needing it, which now only needs to be assigned to a specific group/user
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:userrole: xm-content-reader
        hipposys:role: readonly