# TODO rather replace 'everybody' with functional role 'workflow-user'
definitions:
  config:
    /hippo:configuration/hippo:domains/workflows-read:
      jcr:primaryType: hipposys:domain
      /workflows-domain:
        jcr:primaryType: hipposys:domainrule
        /workflow-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:workflows
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [everybody]
        hipposys:role: readonly
