definitions:
  config:
    /hippo:configuration/hippo:domains:
      /everywhere:
        jcr:primaryType: hipposys:domain
        /all-nodes:
          jcr:primaryType: hipposys:domainrule
          /match-all-types:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:primaryType
            hipposys:type: Name
            hipposys:value: '*'
        /admin:
          jcr:primaryType: hipposys:authrole
          hipposys:userrole: xm.repository.admin
          hipposys:role: admin
        /readonly:
          jcr:primaryType: hipposys:authrole
          hipposys:userrole: xm.repository.reader
          hipposys:role: readonly
