definitions:
  config:
    /hippo:configuration/hippo:domains/content-drafts-readwrite:
      jcr:primaryType: hipposys:domain
      /documents-drafts-domain:
        jcr:primaryType: hipposys:domainrule
        /if-holder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hippostd:holder
          hipposys:filter: false
          hipposys:type: String
          hipposys:value: __user__
        /content-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /content
      /readwrite:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [editor, author]
        hipposys:role: readwrite
