definitions:
  config:
    /hippo:configuration/hippo:domains/defaultread:
      jcr:primaryType: hipposys:domain
      /hippo-translations-domain:
        jcr:primaryType: hipposys:domainrule
        /hippo-translations-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:translations
      /hippo-derivatives:
        jcr:primaryType: hipposys:domainrule
        /hippo-derivatives-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:derivatives
      /user-folders:
        jcr:primaryType: hipposys:domainrule
        /user-folder:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:users
        /exclude-users:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: false
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hipposys:user
      /self:
        jcr:primaryType: hipposys:domainrule
        /match-nodename-with-username:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodename
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: __user__
        /type-hippo-user:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hipposys:user
      /self-groups:
        jcr:primaryType: hipposys:domainrule
        /type-hippo-group:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: nodetype
          hipposys:filter: false
          hipposys:type: Name
          hipposys:value: hipposys:group
        /match-members-with-username:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: hipposys:members
          hipposys:filter: false
          hipposys:type: String
          hipposys:value: __user__
      /hippo-security-node:
        jcr:primaryType: hipposys:domainrule
        /security-node:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:uuid
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:configuration/hippo:security
      # TODO shouldn't hippolog be for cms users only?
      /domain-hippolog:
        jcr:primaryType: hipposys:domainrule
        /hippolog-and-descendants:
          jcr:primaryType: hipposys:facetrule
          hipposys:equals: true
          hipposys:facet: jcr:path
          hipposys:filter: false
          hipposys:type: Reference
          hipposys:value: /hippo:log
      /hippo-modules:
          jcr:primaryType: hipposys:domainrule
          /type-modulefolder:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:path
            hipposys:filter: false
            hipposys:type: Reference
            hipposys:value: /hippo:configuration/hippo:modules
      # TODO rather replace 'everybody' with functional role 'workflow-user'
      /hippo:configuration/hippo:domains/workflows:
        jcr:primaryType: hipposys:domain
        /workflows-domain:
          jcr:primaryType: hipposys:domainrule
          /workflow-and-descendants:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:path
            hipposys:filter: false
            hipposys:type: Reference
            hipposys:value: /hippo:configuration/hippo:workflows
      # TODO rather replace 'everybody' with functional role 'cms-user'
      /hippo:configuration/hippo:domains/frontendconfig:
        jcr:primaryType: hipposys:domain
        /frontendconfig-domain:
          jcr:primaryType: hipposys:domainrule
          /frontendconfig-and-descendants:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:path
            hipposys:filter: false
            hipposys:type: Reference
            hipposys:value: /hippo:configuration/hippo:frontend
      # TODO rather replace 'everybody' with functional role 'cms-user'
      /hippo:configuration/hippo:domains/hippo-namespaces:
        jcr:primaryType: hipposys:domain
        /hippo-namespaces-domain:
          jcr:primaryType: hipposys:domainrule
          /hippo-namespaces-and-descendants:
            jcr:primaryType: hipposys:facetrule
            hipposys:equals: true
            hipposys:facet: jcr:path
            hipposys:filter: false
            hipposys:type: Reference
            hipposys:value: /hippo:namespaces
      /readonly:
        jcr:primaryType: hipposys:authrole
        hipposys:groups: [everybody]
        hipposys:role: readonly
