definitions:
  config:
    /hippo:configuration/hippo:groups/author:
      jcr:primaryType: hipposys:group
      hipposys:members:
        .meta:category: system
        value: []
      hipposys:userroles:
        .meta:category: system
        value: [xm-content-author]
      hipposys:securityprovider: internal
