definitions:
  config:
    /hippo:configuration/hippo:groups:
      /everybody:
        jcr:primaryType: hipposys:group
        hipposys:description: ''
        hipposys:members: ['*']
        hipposys:securityprovider: internal
        hipposys:system: true
        hipposys:userroles:
          .meta:category: system
          .meta:add-new-system-values: true
          value: [xm-content-holder]
      /author:
        jcr:primaryType: hipposys:group
        hipposys:members:
          .meta:category: system
          .meta:add-new-system-values: true
          value: []
        hipposys:userroles:
          .meta:category: system
          .meta:add-new-system-values: true
          value: [xm-default-author-user]
        hipposys:securityprovider: internal
      /editor:
        jcr:primaryType: hipposys:group
        hipposys:members:
          .meta:category: system
          value: []
        hipposys:userroles:
          .meta:category: system
          .meta:add-new-system-values: true
          value: [xm-default-editor-user]
        hipposys:securityprovider: internal
      /admin:
        jcr:primaryType: hipposys:group
        hipposys:members:
          .meta:category: system
          value: []
        hipposys:userroles:
          .meta:category: system
          .meta:add-new-system-values: true
          value: [xm-default-sysadmin-user]
        hipposys:securityprovider: internal
