definitions:
  config:
    /hippo:configuration/hippo:userroles:
      /xm.repository.admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: []
      /xm.system.admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.repository.admin, xm.security.user-admin, xm.security.application-admin]
      /xm.security.viewer:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: []
      /xm.security.user-admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.security.viewer]
      /xm.security.application-admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.security.viewer]
      /xm.content.viewer:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: []
      /xm.content.author:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.content.viewer]
      /xm.content.editor:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.content.author]
      /xm.content.admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.content.editor]
      /xm.repository.reader:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: []
      /xm.default-user.author:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.content.author]
      /xm.default-user.editor:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.content.editor]
      /xm.default-user.system-admin:
        jcr:primaryType: hipposys:userrole
        hipposys:system: true
        hipposys:userroles: [xm.system.admin, xm.content.admin]
