#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set($hyphen = '-')
#set($empty = '')
/content/gallery/${rootArtifactId.replace($hyphen,$empty)}:
  jcr:primaryType: hippogallery:stdImageGallery
  jcr:mixinTypes: ['mix:referenceable', 'hippo:named']
  jcr:uuid: a62d5ba7-424f-4b8e-870e-4493aa74f619
  hippostd:foldertype: [new-image-folder]
  hippostd:gallerytype: ['hippogallery:imageset']
  hippo:name: ${projectName}

